site_name: SFU Cedar
site_description: Documentation for the SFU Tier 3

repo_name: GitHub
repo_url: https://github.com/jburzy01/SFUCedarDocs
edit_uri: 'tree/main/docs'


theme:
    name: readthedocs

nav:
    - Home: index.md
    - Cedar basics: cedar.md
    - ATLAS setup: atlas.md

plugins:
    - search

